version: '2'

services:
  # apollo-quick-start:
  #   image: nobodyiam/apollo-quick-start
  #   container_name: apollo-quick-start
  #   depends_on:
  #     - apollo-db
  #   ports:
  #     - "8080:8080"
  #     - "8070:8070"
  #   links:
  #     - apollo-db

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - apollo-dbdata

  apollo-dbdata:
    image: alpine:latest
    container_name: apollo-dbdata
    volumes:
      - /var/lib/mysql

  consul:
    image: consul
    restart: always
    container_name: consul_server
    network_mode: bridge
    volumes:
      - ./consul:/tmp/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    command: consul agent -data-dir=/tmp/consul -dev -client=0.0.0.0

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    network_mode: bridge

  hystrix-dashboard:
    image: mlabouardy/hystrix-dashboard
    container_name: hystrix-dashboard
    restart: always
    ports:
      - 8088:9002
  
  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaegertracing
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"